# Generated by Django 5.2.4 on 2025-07-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_alter_categoriaprod_id_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contenido',
            field=models.TextField(default='Sin contenido', max_length=100),
        ),
    ]
