# Generated by Django 5.2.4 on 2025-07-29 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_producto_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre_emp', models.CharField(max_length=30)),
                ('apellido_emp', models.CharField(max_length=30)),
                ('telefono_emp', models.CharField(max_length=10)),
                ('email_emp', models.EmailField(max_length=254)),
                ('cargo_emp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono_provee', models.CharField(max_length=10)),
                ('plazo_entrega', models.CharField(choices=[('tres_dias', 'Tres días'), ('dos_semanas', 'Dos semanas'), ('un_mes', 'Un mes')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.empleado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.ordencompra')),
            ],
        ),
    ]
